apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- katib-mysql-deployment.yaml
images:
  - name: $(PRIVATE_REPOSITORY)/mysql
    newTag: "5.6"
    newName: $(PRIVATE_REPOSITORY)/mysql
