apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- stateful-set.yaml
images:
- name: $(PRIVATE_REPOSITORY)/gcr.io/$(project)/application-controller
  newName: $(PRIVATE_REPOSITORY)/gcr.io/$(project)/application-controller
  newTag: latest
