apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: ${PRIVATE_REGISTRY}/osixia/openldap
  newName: ${PRIVATE_REGISTRY}/osixia/openldap
  newTag: latest
- name: ${PRIVATE_REGISTRY}/osixia/phpldapadmin
  newName: ${PRIVATE_REGISTRY}/osixia/phpldapadmin
  newTag: latest
