apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- statefulset.yaml
images:
  - name: $(PRIVATE_REPOSITORY)/busybox
    newTag: "latest"
    newName: $(PRIVATE_REPOSITORY)/busybox
