apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- statefulset.yaml
images:
  - name: ${PRIVATE_REGISTRY}/busybox
    newTag: "latest"
    newName: ${PRIVATE_REGISTRY}/busybox
